version: "3.5"
services:
  vault-server:
    build: .
    container_name: vault-server
    hostname: vault-server
    networks:
      default:
        ipv4_address: 172.18.2.7
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_OIDC_CLIENT_ID=6099f481-2b5e-4010-aa39-e0f184323ad1
      - VAULT_OIDC_CLIENT_SECRET=AKO2FdAi0ioaNJyF0xhGi9qRFU7Th8kAcUEVX6y3bjtc9fHUSQQ2yerpHnTdwZE35VxS99OGNpGnZWXbAtvIhQw
      - VAULT_OIDC_SERVER_URL=https://wlcg.cloud.cnaf.infn.it/
      - VAULT_OIDC_SCOPES=profile,email,offline_access,wlcg,wlcg.groups,storage.read:/,storage.modify:/,storage.create:/
      - VAULT_REDIRECT_URIS=http://localhost:8200/v1/auth/$VPATH/oidc/callback
      - VAULT_ADDR=http://127.0.0.1:8200
    command: vault server -log-level=debug -config=/vault/config/vault.json

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.2.0/24